---

plugins:
  
  # https://github.com/babel/eslint-plugin-babel
  - babel

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env: 
  node: true
  

# https://github.com/babel/babel-eslint
parser: babel-eslint

extends:
  - 'airbnb-base'
  - plugin:import/errors
  - plugin:import/warnings
rules:
  no-console: 0

  import/extensions:
   - 0
   - {json: "always", js: "never"}

